"""Type definitions for the Neptune CLI.

These types mirror the AI service responses and other shared data structures.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


# ==============================================================================
# Enums
# ==============================================================================


class OutputMode(str, Enum):
    """Output format mode for CLI commands."""

    NORMAL = "normal"
    JSON = "json"


class WorkloadKind(str, Enum):
    """Type of workload."""

    SERVICE = "Service"
    BACKEND = "Backend"
    ETL_JOB = "ETLJob"
    UNKNOWN = "Unknown"


class ResourceKind(str, Enum):
    """Type of resource."""

    DATABASE = "Database"
    STORAGE_BUCKET = "StorageBucket"
    SECRET = "Secret"
    UNKNOWN = "Unknown"


class AiLintCategory(str, Enum):
    """Category of AI lint finding."""

    ARCHITECTURE = "architecture"
    RESOURCE_SUPPORT = "resource_support"
    WORKLOAD_SUPPORT = "workload_support"
    CONFIGURATION_INVALID = "configuration_invalid"
    UNKNOWN = "unknown"


class AiLintSeverity(str, Enum):
    """Severity level of AI lint finding."""

    ERROR = "error"
    WARNING = "warning"
    UNKNOWN = "unknown"


# ==============================================================================
# AI Service Types
# ==============================================================================


class Resource(BaseModel):
    """A resource in a platform spec."""

    kind: ResourceKind
    name: str


class Spec(BaseModel):
    """Platform specification generated by AI service."""

    kind: WorkloadKind
    name: str
    resources: list[Resource] = []


class AiLintFinding(BaseModel):
    """A single finding from AI lint."""

    category: AiLintCategory
    code: str
    message: str
    path: str | None = None
    suggestion: str | None = None
    details: dict[str, Any] | None = None
    severity: AiLintSeverity


class AiLintSummary(BaseModel):
    """Summary of AI lint results."""

    errors: int = 0
    warnings: int = 0
    suppressed: int = 0
    blocking: bool = False
    blocking_reason: str | None = Field(None, alias="blockingReason")


class AiLintConfig(BaseModel):
    """Configuration for AI lint behavior."""

    block_on_warnings: bool = Field(False, alias="blockOnWarnings")
    suppressed_codes: list[str] = Field(default_factory=list, alias="suppressedCodes")


class AiLintReport(BaseModel):
    """Complete AI lint report."""

    compatible: bool
    generated_at: datetime = Field(alias="generatedAt")
    errors: list[AiLintFinding] = []
    warnings: list[AiLintFinding] = []
    suppressed: list[AiLintFinding] = []
    summary: AiLintSummary = AiLintSummary()
    config: AiLintConfig = AiLintConfig()


class GenerateResponse(BaseModel):
    """Response from the AI service generate endpoint."""

    platform_spec: Spec
    ai_lint_report: AiLintReport | None = None
    start_command: str


# ==============================================================================
# CLI Output Types
# ==============================================================================


class LintGateAssessment(BaseModel):
    """Assessment of whether lint findings should block deployment."""

    blocking: bool = False
    reasons: list[str] = []


class CommandResult(BaseModel):
    """Base class for command results (for JSON output mode)."""

    ok: bool
    messages: list[str] | None = None
    next_action_command: str = ""


class StatusResult(CommandResult):
    """Result of status command."""

    project: str
    condition: dict[str, Any] | None = None
    url: str | None = None
    env: dict[str, str] | None = None


class ListResult(CommandResult):
    """Result of list command."""

    projects: list[dict[str, Any]] = []


class DeployResult(CommandResult):
    """Result of deploy command."""

    project: str
    ai_lint_report: AiLintReport | None = None
    build: dict[str, Any] | None = None
    deployment: dict[str, Any] | None = None
    final_condition: dict[str, Any] | None = None
    final_url: str | None = None
    final_env: dict[str, str] | None = None


class LintResult(CommandResult):
    """Result of lint command."""

    project: str
    ai_lint_report: AiLintReport | None = None


class GenerateResult(CommandResult):
    """Result of generate spec command."""

    spec_path: str = ""
    ai_lint_report: AiLintReport | None = None


# ==============================================================================
# Template Types
# ==============================================================================


class Template(BaseModel):
    """A project template."""

    name: str
    url: str
    description: str = ""


# Default templates
TEMPLATES: list[Template] = [
    Template(
        name="Python FastAPI",
        url="https://github.com/fastapi/full-stack-fastapi-template",
        description="Full stack FastAPI template with React, PostgreSQL, Docker",
    ),
]
